### ISSUE TITLE
Compatibility with chrome plugins like Evernote's Clearly (or create a new plugin)

### ISSUE THREAD

**Issue by clementpoh** [cameron/squirt#1]
Currently for some web articles, it doesn't successfully extract the text unfortunately. In Chrome, even using plugins like Evernote's Clearly plugin successfully extracts the text. However, when I select the text  and click on Squirt bookmarklet it unfortunately doesn't work.

**Comment by bsnyder** [comment]
+1

**Comment by cameron** [comment]
This isn't specific enough to be a bug report :\

**Comment by bpinaya** [comment]
Well, it would be kind of useful to have at least a workaround :)
