### ISSUE TITLE
Stops reading at "..." in project Gutenberg

### ISSUE THREAD

**Issue by donutsauce** [cameron/squirt#100]
Squirt stops reading at this point in The Moonstone on Project Gutenberg:

---

On this, the disconnected words, and fragments of sentences, which had dropped from Mr. Candy in his delirium, appeared as follows:
"... Mr. Franklin Blake ... and agreeable

---

between the colon and the quotation mark + ellipsis.

**Comment by cameron** [comment]
Works for me. It's still clunky (stops on each period...), but I pushed a fix for this issue this afternoon! Make sure your cache is clear?
