### ISSUE TITLE
Progress bar lack

### ISSUE THREAD

**Issue by vladholubiev** [cameron/squirt#102]
While reading e-book it's useful to see how much have you read.
Also, it would be great if you also add realtime statistic such as: words already read / words at all. It will encourage to read more, won't it?
![bpevhzfxzl 1](https://f.cloud.github.com/assets/3817380/2431078/47ae7aa2-ad19-11e3-8454-d06c3ea8d4a2.png)

**Comment by ofalvai** [comment]
I think a simple progressbar is enough, and the stats would only appear when you hit pause. You don't have time to look at numbers while reading, but a growing progressbar is easy enough to recognise.

**Comment by vladholubiev** [comment]
I completely agree with @ofalvai. He just expressed my ideas.

**Comment by dsernst** [comment]
:+1:

**Comment by aftermathew** [comment]
Upvote for a very simple out of the way progress bar.

**Comment by cameron** [comment]
coming in the next release, which should be this weekend!
