### ISSUE TITLE
Configuration for select word count to show 

### ISSUE THREAD

**Issue by vdvornyk** [cameron/squirt#109]
I want have option to customize word count which shows to me.
I could set more than 1 word at a time. It should be centre line by width.
Width should be set by configuration: for example  i could set count for words in a single line.
If we have more than 1 line than it should center each line of the text.

**Comment by vdvornyk** [comment]
Any comments on my issue?

**Comment by cameron** [comment]
hey @ajaxjquerytools! it's an interesting idea but not one i plan on pursuing in the near term. 

my goal is to keep the product as simple (and configuration-free) as possible. i think multiple words at a time would be pretty cool for a small subset of users who are already capable readers, but i don't have the bandwidth to support the additional complexity for a minority use case.
