### ISSUE TITLE
Find out a way to do this for PDFs...

### ISSUE THREAD

**Issue by eranation** [cameron/squirt#11]
One of the main pains in reading academic papers is that they are all in PDF. I have a lot of readings to do for a graduate course I'm taking, and being able to squirt through all of them via PDF would be a bliss... 

yes, I can copy / paste into pastebin or something, but if there was a way to do it without a workaround it would have been awesome

**Comment by SurenNihalani** [comment]
+1 for this issue. I have the same problem.

**Comment by iamgp** [comment]
They are not. Often there are HTML versions available. Just use that instead!

**Comment by j6k4m8** [comment]
The structure of PDFs prohibits this code from working without some major adjustments. Not a quick fix, so I'd vote we put it on a backburner, or fork the repo for PDF compatibility.

**Comment by iamgp** [comment]
You might be able to convert them to XML then go through that.

**Comment by j6k4m8** [comment]
Anyone have any interest in a companion project for academic papers (that would include support for PDFs, as well as giving extra time for abbreviations or _very_ long words that may require some extra parsing on the reader's part)? I'd contribute if one were around.

**Comment by iamgp** [comment]
Me too.

**Comment by j6k4m8** [comment]
If no one else jumps on this, I've [forked the project](https://github.com/j6k4m8/squirt-academic) but I don't have time to really play with it until the weekend. I'll gladly give read/write to anyone who wants it, or just add PRs or Issues to address.

**Comment by cameron** [comment]
Out of scope of the bookmarklet.
