### ISSUE TITLE
Better compatibility with Better Popup Blocker

### ISSUE THREAD

**Issue by gthiruva** [cameron/squirt#113]
Squirt needs some sort of improvement to avoid conflicting with PopUp blockers.

I've noticed Squirt has trouble with some of the options for the Better PopUp Blocker Chrome Extention (http://optimalcycling.com/other-projects/better-pop-up-blocker/). Though, I'm not sure which option yet. Right now, I have to whitelist a site under BPB to get the Squirt Bookmarklet to work.

Without getting whitelisted on a site, Squirt is still able to draw its content box. However, it fails to be able to do the countdown and read text.

However, I also have a similar extension (bit.ly bookmarklet: https://chrome.google.com/webstore/detail/bitly-%E2%99%A5-your-bitmarks/iabeihobmhlgpkcgjiloemdbofjbdcic) that uses JS to draw it's own `<div>` over arbitrary pages and it has no problems interfering with BPB.

So, I think whatever bit.ly is doing, is perhaps a good template to follow in Squirt to avoid getting blocked.

**Comment by cameron** [comment]
i doubt very much it's the popup blocker as i'm not launching any popups. have seen this same bug report before and it was due to https issues, which have been fixed if you go ahead and [re-install](http://squirt.io/install.html) the bookmarklet.
