### ISSUE TITLE
SSL is stopping Squirt

### ISSUE THREAD

**Issue by luczyna** [cameron/squirt#118]
When I try to use Squirt on a page loaded with https, it does not work and returns the following:

```
[blocked] The page at 'https://medium.com/what-im-reading-on-medium/7958dae1d27b' was loaded over HTTPS, but ran insecure content from 'http://www.squirt.io/bm/squirt.js': this content should also be loaded over HTTPS.
```

**Comment by cameron** [comment]
This has been fixed, but you have to re-install the bookmarklet for it to work: http://squirt.io/install.html
