### ISSUE TITLE
Option to Change fonts to Sans Serif

### ISSUE THREAD

**Issue by forddavis** [cameron/squirt#133]
The font chosen is pretty good for a serif font (Georgia?) but RSVP has been shown to work better with sans serif fonts. The Serifs (those extra lines and triangular details on the letters) make text harder to read and are only really good for making a printed document look more formal. It would be great to have Arial, Helvetica, or even a monospace font like Andale Mono. Google Open Sans is really nice to read too. You ditched the outdated reading style, ditch the old fonts too.

**Comment by cameron** [comment]
Hmm, interested to see research on this. My intuition and experience is that the serifs actually make the words easier to recognize by adding a bit more uniqueness to their shape, but that could be hocus-pocus. An option to change font is coming in the next release, which will happen today or tomorrow.

**Comment by forddavis** [comment]
I know spritz has done testing and determined to use sans, which was consistent with what I thought. On the other hand I dug into it and there is some debate into the matter. Apparently most people have a preference and think they read their favorite better even when this isn't the case. Anyway thanks for sharing your project.

**Comment by cameron** [comment]
Sans serif font option is live!
