### ISSUE TITLE
Bookmarklet does not work on Chrome or Safari (OS X)

### ISSUE THREAD

**Issue by ecwilsonaz** [cameron/squirt#135]
When I click the bookmarklet on any article, it opens but instead of showing the article text, it just says:

"Replace your existing bookmarklet with this one..." followed by some more text.

I have removed/readded the bookmarklet many times now to no avail.

OS X 10.9.2
Chrome Version 34.0.1847.116
Safari Version 7.0.2 (9537.74.9)

Bookmarklet code:

```
javascript:(function()%7Bsq=window.sq;if(sq&&sq.closed)%7Bwindow.sq.closed&&window.document.dispatchEvent(new%20Event('squirt.again'));%7Delse%7Bsq=window.sq%7C%7C%7B%7D;sq.version='0.2.0';sq.host='//squirt.io';sq.userId='ce6b7e16-0b05-4e5c-bde5-ac5f0580f083';sq.j=document.createElement('script');sq.j.src=sq.host+'/bm/squirt.js';document.body.appendChild(sq.j);%7D%7D)();
```

**Comment by rcastaneda** [comment]
I am having this issue as well. I also happen to have Readability installed. If I first use readability to process a page and then use the Squirt bookmarklet, then it will function as expected.

I suspect that Squirt's reference to Readability needs to be updated.

**Comment by cameron** [comment]
Pushed a big batch of updates. Try again?

**Comment by ecwilsonaz** [comment]
Works!

--Eric

**Comment by cameron** [comment]
Noice!
