### ISSUE TITLE
SQUIRT crashing browsers

### ISSUE THREAD

**Issue by andersonpem** [cameron/squirt#139]
I see since I updated squirt to the new link I can't read anywhing in Chrome or Firefox. It crashes after allocate more than 2GB of my memory.

**Comment by cameron** [comment]
What OS are you running?

**Comment by andersonpem** [comment]
Windows 8.1 Update 1

**Comment by andersonpem** [comment]
Google Chrome 34.0.1847.116 m
Mozilla Firefox 28.0

**Comment by andersonpem** [comment]
I think I see what's the problem. I'm trying to read a very large document. In the previous version, it was possible without glitches. In this new version, it looks like the script allocate memory in an anormal way and then the browser crash.
I'm trying to read the brazilian constitution, a very large text which you can find here:
http://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm

**Comment by MaddAddaM** [comment]
The bookmarklet used to work nicely on iPads as well, but this update results in a guaranteed crash of the browser now.  I'm guessing that this issue is also the cause of this becoming unusable on iPads (latest iOS 7.1).

Let me know if you need any help testing.  I love Squirt and I'm happy to test if needed.

**Comment by cameron** [comment]
@andersonpem haha. i knew this would be a problem but side-stepped the issue in favor of getting something out the door. i'm sorry it's biting you. it's on the TODO list, but is not very high priority, as it's an edge use case. definitely something i'd consider accepting pull requests for as soon as i update the public repo :)

**Comment by andersonpem** [comment]
Ah, and if you could get back the function which displays how much words I read I'd be glad too. Thanks ;)

**Comment by cameron** [comment]
You're welcome to poke around in the git repo :)
