### ISSUE TITLE
New Version Won't Adjust WPM

### ISSUE THREAD

**Issue by trainofthought4** [cameron/squirt#143]
Hey all-

I just installed a new version of the bookmark after being prompted. I'm using Safari 7.0.2 and the problem is that the WPM starts off as "undefined WPM" and starts moving way too fast to read any of the words at all. When I try to adjust the WPM using the up and down arrows it says "NaN WPM," which doesn't change the speed at all. And it won't change from there. With whatever glitch this is, the app is unusable.

**Comment by cameron** [comment]
Works for me on Safari 7.0.3. Unlikely that I'll get to fix this :(
