### ISSUE TITLE
< li > tags - problematic when reading part of a page

### ISSUE THREAD

**Issue by vladtoader** [cameron/squirt#17]
< li > tags seem to be problematic when using the feature of only reading part of the page (i.e. highlighting text on the page). The following (spaces in li tag are intentional here):
<code>
< li>"This is the first item."< /li>
< li>"Followed by the second one."< /li>
</code>
... causes the following display:

item.
Followed

... in other words, "Followed" is displayed at the same time as "item" and it shows up underneath it.  As an example, use the site shown in the squirt.io bookmarklet youtube video tutorial http://zenhabits.net and highlight the bullet-point list.

**Comment by cameron** [comment]
Fixed :)
