### ISSUE TITLE
Bookmark icon not working

### ISSUE THREAD

**Issue by rickstaa** [cameron/squirt#187]
Dear developers,

Is there a way to assign a favicon to the booklet?

Thanks alot in advance,
Greetings

**Comment by RayBB** [comment]
Looks like this currently isn't possible.
https://stackoverflow.com/questions/521040/how-to-have-favicon-icon-set-when-bookmarklet-dragged-to-toolbar

**Comment by rickstaa** [comment]
Ah I see thanks for the response.
