### ISSUE TITLE
Close squirt when escape is pressed.

### ISSUE THREAD

**Issue by clementpoh** [cameron/squirt#2]
This is a really awesome, but I have some requests.

Clicking outside of the panel is the only way to close the overlay. It would be good if it could also be closed by pressing the escape button or something similar.

**Comment by chid** [comment]
So adding a keydown even which triggers hideGUI()?

**Comment by dmtroyer** [comment]
keyboard shortcuts in general would be great.

**Comment by akrikos** [comment]
I agree. Would make it much more usable without fumbling for the mouse to pause.
Some shortcuts that make sense to me:
esc: close squirt
up: speed up by 50 wpm
down: slow by 50 wpm
left: << 10s
space: pause

**Comment by goodforenergy** [comment]
Agreed! This would make an awesome tool even better. Especially space to pause and escape to close. If you get interrupted when you're reading at a fast speed you can quickly lose your place before you manage to pause.

**Comment by cebe** [comment]
> esc: close squirt
> up: speed up by 50 wpm
> down: slow by 50 wpm
> left: << 10s
> space: pause

:+1:

**Comment by cameron** [comment]
Closing in favor of other issues mentioning shortcuts.
