### ISSUE TITLE
Add "where you are" in the article

### ISSUE THREAD

**Issue by carlisia** [cameron/squirt#21]
Similar to #18, add an indicator of what percentage of the article there is still left.

**Comment by j6k4m8** [comment]
And, if you leave the Squirt window, the page should scroll to where you are in the article (and start there again when you return.)

**Comment by cameron** [comment]
That's a good idea, @j6k4m8. Closing in favor fo #18

**Comment by gsingh93** [comment]
I think showing how much time is remaining for reading the article is a good idea, but I like @j6k4m8's suggestion as well. Currently, there is no automatic pausing feature for images or code, so if there's a point where I need to pause to look at an image, I have to find where it is in the page. I think when you pause the extension should autoscroll to that point.
