### ISSUE TITLE
Detect and pause for code examples

### ISSUE THREAD

**Issue by ultimatedelman** [cameron/squirt#23]
If there were a way to detect when code examples were being shown, a huge improvement would be to show the code example in its entirety and pause, allowing the user to continue reading after digesting the code example. Words are easy to garner meaning from in a flash, but code obviously requires symbols and has a lot more meaning packed into each word/line. This would make going through technical documentation UNBELIEVABLE.

**Comment by iamgp** [comment]
Could do this by detecting < code> < pre>?

**Comment by cameron** [comment]
Out of scope at the moment—not closely enough in line with the majority use case. Would love to see it working, though!

**Comment by gsingh93** [comment]
+1 for this feature. I was just about to suggest it when I decided to search the issues for it first. I read a lot of programming books and articles online so this would be awesome.

Maybe you could implement a more general "pause for these things" feature. For example, if those settings were enabled, it would pause and show the image you're at, or the video, or in this case the code snippet. That would satisfy the general public and hopefully the code would be reusable enough to add in more things to pause at.
