### ISSUE TITLE
Ellipsis "..." hangs the squirt.io reader permanently

### ISSUE THREAD

**Issue by levskaya** [cameron/squirt#26]
I've replicated this bug on many different sites and sources now.  This bug replicates on chrome, safari, and firefox.

Anytime an ellipsis ,i.e. "..." appears in the text, the squirt.io reader halts. (never showing the word immediately before the ellipsis)

e.g. at the top of this blog:
http://andrewgelman.com/2014/03/11/stop-publishing-journals/

**Comment by btracey** [comment]
I don't know if this is related, but it also hangs on non-pure text, for example, on project gutenberg it hangs at the section bar (right after the title)

http://www.gutenberg.org/files/98/98-h/98-h.htm#link2H_4_0016

If this is a different issue let me know and I can open a new one.

**Comment by jamesanthonyferguson** [comment]
Also found this bug, but I think it's more generic than just ellipses - I've found it occurs when multiple punctuation marks are used next to each other such as ., and !?

**Comment by btharada** [comment]
In addition to ellipses, the app also seems to halt at em- and en-dashes (– and —).

**Comment by j6k4m8** [comment]
I haven't had trouble with either dash, but I have with the dot-comma in things like

> Which occurred at 6 a.m., Tuesday morning.

I have a feeling this is related to more than one punctuation mark in a row (perhaps the dashes @btharada saw were post-processed versions of '--' and '---').

**[EDIT]** This issue lives [here](https://github.com/cameron/squirt/blob/gh-pages/bm/squirt.js#L285), and raises the following error:

> Uncaught TypeError: Cannot read property 'offsetLeft' of undefined 

My suspicion is that [this regex](https://github.com/cameron/squirt/blob/gh-pages/bm/squirt.js#L228) is to blame for incorrectly categorizing multiple punctuation marks as a 'word', or perhaps it's being considered a word, and then punctuation is stripped and you're left with an `undefined`, but I don't have the time to investigate it now.

**Comment by alexander-pecheny** [comment]
two dots ‘..’ also cause error

**Comment by ericridgeway** [comment]
Since the earlier example links of this bug seem to be dead right now, here's a currently working one: http://www.orbitbooks.net/excerpt/the-lascars-dagger/

As in: "You’ll be too late . . . too late"

It only reads up to: "You'll be too"

**Comment by bethaitman** [comment]
I've found this too with ellipses - squirt just stops when it hits them.

**Comment by cameron** [comment]
aee3e4cd77b759e77348aed03aff2aa73db027a0 should resolve this, while exposing the fact that word splitter needs some love.
