### ISSUE TITLE
option to pause between paragraphs

### ISSUE THREAD

**Issue by clementpoh** [cameron/squirt#27]
It would be good if there were the option to pause or show down for a second or so between paragraphs. Right now it just zooms steadily through, while the content's context has changed, it can be slightly confusing...

**Comment by cameron** [comment]
It actually pauses 4x the normal interval after paragraphs. 3x after periods, 2x after commas, and 1.3x after short words. There are some other rules, as well, but I agree that configuring them would be nice :)
