### ISSUE TITLE
In Firefox 27.0.1, selection is not used for reading

### ISSUE THREAD

**Issue by lonbinder** [cameron/squirt#28]
Tested in Chrome, works fine. In FF, select text, then click bookmarklet. Instead of reading just selected text, reads the whole page.

**Comment by Coornail** [comment]
I can confirm that it happens.

The issue is that the Selection object in Firefox doesn't have a `type` property: https://developer.mozilla.org/en-US/docs/Web/API/Selection

**Comment by zloster** [comment]
The selection object in Firefox has `toString` method:
https://developer.mozilla.org/en-US/docs/Web/API/Selection/toString
