### ISSUE TITLE
paragraph break bug

### ISSUE THREAD

**Issue by aixnr** [cameron/squirt#30]
![paragraph break bug](http://s29.postimg.org/urd7z3zev/Screen_Shot_2014_03_12_at_5_58_06_PM.png)

I was reading this article on TechCrunch
http://techcrunch.com/2014/03/11/wikipedia-co-founder-jimmy-wales-accidentally-starts-a-bitcoin-donation-campaign-for-wikipedia/

It appears that Squirt can't handle well with the paragraph break.

**Comment by emarthinsen** [comment]
+1 on this. I've noticed it on several articles.

**Comment by darkobodnaruk** [comment]
+1

**Comment by cameron** [comment]
Try again? https://github.com/cameron/squirt/pull/19 May have addressed it.

**Comment by aixnr** [comment]
I've tried it as I wrote in a comment on #19. The fix works. Thanks!
