### ISSUE TITLE
Allow jumping in HTML

### ISSUE THREAD

**Issue by btracey** [cameron/squirt#33]
Trying to read, say A Tale of Two Cities, one may want to skip to a certain chapter, for example http://www.gutenberg.org/files/98/98-h/98-h.htm#link2H_4_0016. However, squirt starts at the top of the page.

**Comment by ultimatedelman** [comment]
you can highlight what you want to read and then hit squirt

**Comment by btracey** [comment]
This does not work for me on the Gutenberg site linked (Firefox 27.0.1, OSX 10.9.2)

**Comment by j6k4m8** [comment]
Couldn't reproduce — selection worked fine for me. Can you explain the issue a little more?

**[EDIT]** There is a known bug in Firefox. Check out #45.

**Comment by cameron** [comment]
Closing, noted that gutenberg could be better supported.
