### ISSUE TITLE
Show sentences instead of just words.

### ISSUE THREAD

**Issue by ChrisCinelli** [cameron/squirt#34]
Add an option to show 3, 5, 7 or 9 words at the time and to adjust the speed accordingly.

**Comment by nomicode** [comment]
Squirt is designed to eliminate saccades (eye movements) and so presenting two or more words at once is likely to significantly reduce the effectiveness of the tool.

**Comment by ChrisCinelli** [comment]
Have you ever gone through any speed reading course?

For example the wonderful Evelyn Wood Reading Dynamics ( http://www.ewrd.com/ewrd/evelynwood_readingdynamics.asp )
Or just the basic in http://www.amazon.com/Speed-Reading-Dummies-Richard-Sutz/dp/0470457449 ? 
When you normally read your eyes do not stop on every single word but on phrases. With practice you can increase the number of words that you are able to read at the time. That will actually increase the reading speed, not diminish it.

See also:
- http://www.irisreading.com/speed-reading/increase-your-reading-speed-by-reducing-your-fixation-points/
- And http://www.readspeeder.com/
- http://www.bcs.rochester.edu/courses/crsinf/152/13_Reading.pdf
- Just Google "speed reading fixation points"

**Comment by nomicode** [comment]
Nope, I haven't. That's interesting info. Thanks!

**Comment by cameron** [comment]
Thanks for the suggestion, but it's outside the scope of the project right now!

**Comment by chicocaramelo** [comment]
There could be a range of three or four words before and after the current word, the sentence could be "crawling" (jumping word from word) from right to left on screen, maybe. I wouldn't go faster with this feature, but I think it would enhance understanding.
