### ISSUE TITLE
Using Squirt many times breaks it

### ISSUE THREAD

**Issue by iamgp** [cameron/squirt#36]
(Mac, Chrome)

If I select some words then run squirt on them, and then select different words and try run squirt on THAT, it doesn't work? It just shows as:

![image](https://f.cloud.github.com/assets/170375/2405509/9a5f8eb8-aa52-11e3-83a4-d5fa5ff41e5d.png)

**Comment by cameron** [comment]
Can't repro. Closing until more specifics are provided.
