### ISSUE TITLE
Does not work on kernel.org

### ISSUE THREAD

**Issue by AshKash** [cameron/squirt#40]
Was browsing:
https://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/2.0.0.txt

**Comment by daveloyall** [comment]
Probably a dupe of #5

**Comment by AshKash** [comment]
Confirmed that the problem is due to https. This seems to be working fine:
http://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/2.0.0.txt

**Comment by cameron** [comment]
thanks :)
