### ISSUE TITLE
Remember my WPM setting

### ISSUE THREAD

**Issue by j6k4m8** [cameron/squirt#41]
Perhaps this is already extant, but simply doesn't work for me. Every time I hit the bookmarklet, it's set back to 400WPM — even though it should remember that I want it at 950.

**Comment by rr326** [comment]
+1  Also, maybe a button on the main reading page which is a +50 or -50.  So it remembers where you were last, but can easily move up or down a bit

**Comment by mearns** [comment]
+1

**Comment by peteruithoven** [comment]
How we solved this in Jetzt: https://github.com/ds300/jetzt/blob/master/localstorage-config.js

**Comment by stuttgarter** [comment]
+1

**Comment by cameron** [comment]
@peteruithoven, I take it extensions get treated akin to domains w/r/t cookies and localStorage? Bookmarklets can certainly set user preferences, but they will only apply to the current domain.

**Comment by lbain** [comment]
+1

**Comment by xdumaine** [comment]
Could you allow the default to be editable in the bookmarklet? That way the user can set their own default to be used on every page, even if it's a different domain. Less ideal than being able to set/save it through the UI, but it would still then go to a user configurable default, and not a hard-coded one.

**Comment by SpicyPete** [comment]
+1
Having to increase the speed every time I use this is my only major gripe.
