### ISSUE TITLE
Squirt stops at words, ending with three dots...

### ISSUE THREAD

**Issue by AlexVPopov** [cameron/squirt#46]
If I select a text and within the text there are three dots, the last word squirt will show will be the word immediately before the last one. Example:

> But what the heck is GitHub... and why are developers so excited about it?

If I select this sentence and click the bookmarklet the last word I will see will be "is" and then the pane will just stay empty and nothing will happen.

**Comment by 1ace** [comment]
Duplicate of #26

**Comment by AlexVPopov** [comment]
Sorry, hadn't seen it. Thanks for pointing out.
