### ISSUE TITLE
Squirt not working dn.se

### ISSUE THREAD

**Issue by kristoffernolgren** [cameron/squirt#51]
One of swedens largest news-websites.

here is a sample url
http://www.dn.se/nyheter/sverige/internationella-aklagarmyndigheten-inleder-forundersokning-om-mord-pa-horner/

Here are the errors
Uncaught TypeError: Cannot call method 'match' of undefined squirt.js:465
Uncaught TypeError: Cannot read property 'offsetLeft' of undefined squirt.js:285

browser: latest version of chrome, no plugins.

**Comment by j6k4m8** [comment]
This is another manifestation of the error seen in #26.

**Comment by cameron** [comment]
If it's #26, then it should be good to go :)
