### ISSUE TITLE
Fail better

### ISSUE THREAD

**Issue by rr326** [cameron/squirt#52]
Some pages squirt simply does nothing -eg: https://d4l3.com/dreams

When that happens, at least throw an error or something so I know that you tried and just can't do that page.  The first 3 pages I tried didn't work and I got no feedback and I wondered if I had installed it properly.

**Comment by daveloyall** [comment]
This is NOT a dupe of #5.  That issue is why the bookmarklet doesn't work, but this issue is about better error reporting.

**Comment by cameron** [comment]
This is not an issue of error handling, but of SSL. Squirt does not work on https sites, currently. In the works :)
