### ISSUE TITLE
Availability on mobile devices

### ISSUE THREAD

**Issue by skacperski** [cameron/squirt#57]
I would love to use it on my iPhone or iPad. Is it possible with some hack?

**Comment by j6k4m8** [comment]
There is an installation guide [here](https://github.com/cameron/squirt/blob/gh-pages/install-mobile.md). (I also just PR'd a version that includes Android instructions.)

**Comment by skacperski** [comment]
Great article… but there is no code to copy :)
![Uploading Screen Shot 2014-03-13 at 8.16.32 PM.png . . .]()

**Comment by j6k4m8** [comment]
I believe the code is injected at render-time, unless I misunderstood the initial file.

**Comment by skacperski** [comment]
There is a place for the code with border around it but without the code :) Anyway I've managed to figure it out by myself. It works exactly the same as adding it on the Desktop.

**Comment by thmoeller** [comment]
Safari on IOS 7.1 -> Error: Cannot open page because it is a local file
On Ipad2 and Iphone 
The code i inserted "<pre class="bookmarklet"></pre>"

**Comment by cameron** [comment]
Out of scope for the time being :)
