### ISSUE TITLE
No LICENSE.md file

### ISSUE THREAD

**Issue by cjb** [cameron/squirt#6]
Hi!  Please could you choose a copyright license for Squirt?  At the moment it's "closed source" because no license is chosen, would be awesome to have this under e.g. BSD license.  Thanks!

**Comment by cperrin88** [comment]
That is not totally true: http://choosealicense.com/no-license/

**Comment by MrNice** [comment]
I've submitted a Pull Request to add an MIT license. Given the nature of the project, I would be surprised if Cameron wanted a more restrictive license.

**Comment by nomicode** [comment]
@cperrin88 that page is irresponsible to present no license as an OSS licensing choice. But it does at least include the following: "the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend."

@MrNice I commented on your PR. I think Apache License would be good for it's contribution protections.

**Comment by MrNice** [comment]
@nslater I've submitted a separate pull request ( https://github.com/cameron/squirt/pull/61 ) that holds the apache license.

**Comment by cperrin88** [comment]
@nslater The third paragraph might also be interesting for this project in it's current state:

> For example, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository.

But I agree that a license is the better way

**Comment by nomicode** [comment]
Thanks @MrNice!

**Comment by cameron** [comment]
Apache! Hooray!

**Comment by cjb** [comment]
Thanks @cameron!
