### ISSUE TITLE
Use Squirt in mobile app

### ISSUE THREAD

**Issue by acousticksan** [cameron/squirt#62]
Can I use Squirt in mobile apps? I think that mobile reader with your technology can become very interesting decision.
P.S. Sorry for my poor english, I hope you understand me)

**Comment by j6k4m8** [comment]
It is not possible to 'inject' into a mobile app, though it can be used on a mobile device through the browser. Take a look at #58.

**Comment by acousticksan** [comment]
Why? What about Phonegap?

**Comment by j6k4m8** [comment]
Ah, I thought you meant in existing apps. Check the licensing, but I believe it is permitted to add Squirt to apps you're developing.

**Comment by cameron** [comment]
Knock yourself out! And send us a link if you do :)
