### ISSUE TITLE
Abbreviations show up as separate letters

### ISSUE THREAD

**Issue by malcolmocean** [cameron/squirt#67]
On [this article](http://www.nytimes.com/2014/03/16/magazine/silicon-valleys-youth-problem.html), things like C.E.O. and M.I.T. are displayed sequentially and slowly, as if they were separate sentences. I think it should be fairly straightforward to detect this sort of thing and call it a word.

**Comment by j6k4m8** [comment]
Take a look at #43, might be a dupe.

**Comment by malcolmocean** [comment]
Yup, dupe of #43
