### ISSUE TITLE
Words joined by dashes show up together

### ISSUE THREAD

**Issue by mearns** [cameron/squirt#69]
Words joined by unicode em-dashes (U+2014) show up as a single word, making it very hard to read them. I imagine this probably happens with some other non-ASCII characters as well.

See for instance http://nautil.us/issue/11/light/20-ways-to-see-the-light

**Comment by j6k4m8** [comment]
See #3 for some more discussion on this matter (plus #26 for more talk on non-ascii bugs).

**Comment by cameron** [comment]
Also #15
