### ISSUE TITLE
Squirt ignores spaces before links

### ISSUE THREAD

**Issue by nomicode** [cameron/squirt#72]
In the following test case:

https://gist.github.com/nslater/9536924

https://dl.dropboxusercontent.com/u/3759180/gist/9536924/squirt-test.html

Squirt ignores the space between a link and a word that precedes it.

Example text:

```
Squirt merges words into the following links.
```

Where the word "links" is a hyperlink, Squirt displays that as one large word, "followinglinks".

**Comment by arbrown** [comment]
I have seen similar behavior with italics.  I wish I would have looked at the markup.  It might have been a `span` or some other tag.

**Comment by nomicode** [comment]
Working on a fix. Should have a PR soon.

**Comment by cameron** [comment]
Closing in favor of  #39. @nslater how's this coming along?
