### ISSUE TITLE
Use a sans-serif font, or provide an option

### ISSUE THREAD

**Issue by xdumaine** [cameron/squirt#73]
Spritz uses a sans-serif font, and is much easier to read. Make this default, or give a "serif/sans serif font' option in the menu panel.

**Comment by isheff** [comment]
++

**Comment by nomicode** [comment]
A generalised custom CSS option would solve this. Would also help with custom colours, which may be helpful for some people with reading impairments.

**Comment by cameron** [comment]
See #29
