### ISSUE TITLE
Cannot read property 'offsetLeft' of undefined

### ISSUE THREAD

**Issue by GeorgeGray** [cameron/squirt#84]
# Outline

Squirt throws 'Uncaught TypeError: Cannot read property 'offsetLeft' of undefined' after hitting the text 

**N.Y.,**

after displaying:

**N.**

When then Stops the playback.
# Steps To Reproduce
1. Go to http://www.sptimes.com/2005/01/28/Tampabay/After_the_sky_fell.shtml
2. Select the body text of the article
3. Hit the Squirt button on bookmark bar
4. Wait until the Text mentioned above it hit.

**Comment by j6k4m8** [comment]
I think this is the same issue mentioned in #26 — it appears to take place in all instances of multiple punctuation marks in a row (`.,`, `...`, `--`, etc)

**Comment by GeorgeGray** [comment]
I think that's likely j6k

**Comment by cameron** [comment]
Indeed! It's fixed, although it's quite a rough edge (treats it as the end of a sentence or other punctuation. Next up is a fix for the word splitting. 

aee3e4cd77b759e77348aed03aff2aa73db027a0
