### ISSUE TITLE
Reading stops on "..."

### ISSUE THREAD

**Issue by Flati** [cameron/squirt#87]
The first article I tried with this "plugin" worked very well until it hit the "..." about 1/4 of the way through.

http://www.mbl.is/frettir/innlent/2014/03/14/banna_alla_sima_i_keppnisferdum/

**Comment by j6k4m8** [comment]
See #26.

**Comment by cameron** [comment]
Should work now :) aee3e4cd77b759e77348aed03aff2aa73db027a0
