### ISSUE TITLE
Package squirt as a browser extension

### ISSUE THREAD

**Issue by CitizenOfRome** [cameron/squirt#89]
You could easily package squirt as a browser extension, with a browser-button-based trigger for browsers like Chrome, Firefox & IE with [Cross-Rider](http://crossrider.com/)

I've built a few such extensions & could help you build it, if you'd like.

**Comment by CitizenOfRome** [comment]
Just went ahead and built it: https://github.com/DoersGuild/squirt-crossrider

Let me know if you have a problem with it being public & I'll make it private

**Comment by nomicode** [comment]
Might be cool to merge this into the main repo.
