### ISSUE TITLE
CDATA Javasript appears in text

### ISSUE THREAD

**Issue by programmdesign** [cameron/squirt#92]
If I click on the Squirt bookmarklet on www.zeit.de, it will display hidden CDATA javascript text. I am using Chrome.
![screen shot 2014-03-14 at 21 11 29](https://f.cloud.github.com/assets/4633284/2425425/f53d3160-abb4-11e3-9d6c-37f2cf015674.png)

// <![CDATA[  if (typeof ...

**Comment by cameron** [comment]
Closing in favor of #12
