### ISSUE TITLE
A quick break between paragraphs?

### ISSUE THREAD

**Issue by lukavida** [cameron/squirt#95]
Reading the entire text in one breath makes it less understandable then when the text is structured in paragraphs and sections. Paragraphs enable readers to understand the structure and connect sentences to certain points the text is communicating.

Quick pause (one word length) between paragraphs would help immensely in understanding the text.

**Comment by cameron** [comment]
This is already the case. We pause 4x the normal interval on line breaks, 3x on periods, 2x on commas, and 1.3 on short words (pause for long words coming this weekend).
