### ISSUE TITLE
Use full LICENSE text

### ISSUE THREAD

**Issue by nomicode** [cameron/squirt#96]
The LICENSE at the moment uses the recommended boilerplate, but if you look at the wording, it only licenses the LICENSE file itself. The full text of the Apache License 2.0 should be copied into this file.

**Comment by cameron** [comment]
That's not intuitive to me. Would copying the full text expand the scope of the license to the whole repository? Adding something to the README that says "this project is licensed under the apache license specified in LICENSE" seems more obvious, but I'm not well-versed in LICENSEing.

**Comment by nomicode** [comment]
Well, at the moment, all you've done is license the LICENCE file itself. ;) If you put the actual license text in LICENSE, that should be good enough to license the whole repo. If you want to make it more explicit (you don't have to) you could note it in the README too.

**Comment by cameron** [comment]
Thanks :) b89b12b71240f37915efeaa0489b23fd1922ec71

**Comment by nomicode** [comment]
:+1:
