### ISSUE TITLE
can't read page when javascript is blocked for the TARGET site  i.e. the one you are trying to read not your site 

### ISSUE THREAD

**Issue by Big-Kate** [cameron/squirt#99]
what your saying is that squirt wont work unless No Script is turned off?

that squirt io will only work if I allow any JavaScript Malware on any site  i visit to have free access to my machine?

if so that should be put in large clear letters at the front that its party time for scriptkiddies if you want to use squirt.io

but i don't believe you mean that, i suspect your tired and misread what I said

**Comment by cameron** [comment]
oops. sorry :) see my question on the origin issue!
